// A large, best-effort list of real, well-known US high schools per state —
// mostly large public schools in major cities/metro areas, plus a handful of
// well-known private/prep schools — used so the large majority of HS
// prospects/players get a genuine school name instead of a procedurally
// generated placeholder. Not exhaustive (there are ~24,000 public high
// schools in the US alone) and not verified against an official database;
// treat it the same as the rest of this game's real-world flavor data
// (real team/conference names, real cities) — accurate in spirit, not an
// audit of any specific roster or season. Keys match the 2-letter state
// codes used throughout engine/regions.ts and engine/cities.ts.
//
// Each entry also carries its real host city/suburb so highSchools.ts can
// weight selection toward whichever real school is actually closest to a
// given player's hometownCity, instead of picking uniformly at random
// anywhere in the state.
export interface RealHighSchool {
  name: string;
  city: string;
}

export const REAL_HIGH_SCHOOLS_BY_STATE: Record<string, RealHighSchool[]> = {
  AL: [
    { name: "Vestavia Hills High School", city: "Vestavia Hills" }, { name: "Hoover High School", city: "Hoover" },
    { name: "Mountain Brook High School", city: "Mountain Brook" }, { name: "Auburn High School", city: "Auburn" },
    { name: "Homewood High School", city: "Homewood" }, { name: "Spain Park High School", city: "Hoover" },
    { name: "Hewitt-Trussville High School", city: "Trussville" }, { name: "Thompson High School", city: "Alabaster" },
    { name: "Bob Jones High School", city: "Madison" }, { name: "Huffman High School", city: "Birmingham" },
    { name: "Central High School of Tuscaloosa", city: "Tuscaloosa" }, { name: "Murphy High School", city: "Mobile" },
    { name: "Prattville High School", city: "Prattville" }, { name: "Enterprise High School", city: "Enterprise" },
  ],
  AK: [
    { name: "East Anchorage High School", city: "Anchorage" }, { name: "West Anchorage High School", city: "Anchorage" },
    { name: "Dimond High School", city: "Anchorage" }, { name: "Service High School", city: "Anchorage" },
    { name: "Juneau-Douglas High School", city: "Juneau" }, { name: "West Valley High School", city: "Fairbanks" },
    { name: "Lathrop High School", city: "Fairbanks" }, { name: "Chugiak High School", city: "Chugiak" },
    { name: "Bartlett High School", city: "Anchorage" }, { name: "South Anchorage High School", city: "Anchorage" },
  ],
  AZ: [
    { name: "Brophy College Preparatory", city: "Phoenix" }, { name: "Chaparral High School", city: "Scottsdale" },
    { name: "Desert Vista High School", city: "Phoenix" }, { name: "Mountain Pointe High School", city: "Phoenix" },
    { name: "Corona del Sol High School", city: "Tempe" }, { name: "Hamilton High School", city: "Chandler" },
    { name: "Xavier College Preparatory", city: "Phoenix" }, { name: "Perry High School", city: "Gilbert" },
    { name: "Sandra Day O'Connor High School", city: "Phoenix" }, { name: "Cactus Shadows High School", city: "Cave Creek" },
    { name: "Saguaro High School", city: "Scottsdale" }, { name: "Pinnacle High School", city: "Phoenix" },
    { name: "Basha High School", city: "Chandler" }, { name: "Red Mountain High School", city: "Mesa" },
  ],
  AR: [
    { name: "Little Rock Central High School", city: "Little Rock" }, { name: "Bentonville High School", city: "Bentonville" },
    { name: "Fayetteville High School", city: "Fayetteville" }, { name: "Conway High School", city: "Conway" },
    { name: "Rogers High School", city: "Rogers" }, { name: "Bryant High School", city: "Bryant" },
    { name: "Cabot High School", city: "Cabot" }, { name: "North Little Rock High School", city: "North Little Rock" },
    { name: "Jonesboro High School", city: "Jonesboro" }, { name: "Pulaski Academy", city: "Little Rock" },
  ],
  CA: [
    { name: "Long Beach Poly High School", city: "Long Beach" }, { name: "Mater Dei High School", city: "Santa Ana" },
    { name: "Fairfax High School", city: "Los Angeles" }, { name: "Beverly Hills High School", city: "Beverly Hills" },
    { name: "Venice High School", city: "Los Angeles" }, { name: "Crenshaw High School", city: "Los Angeles" },
    { name: "Dorsey High School", city: "Los Angeles" }, { name: "Compton High School", city: "Compton" },
    { name: "Inglewood High School", city: "Inglewood" }, { name: "Fremont High School", city: "Los Angeles" },
    { name: "Narbonne High School", city: "Los Angeles" }, { name: "Gardena High School", city: "Gardena" },
    { name: "Redondo Union High School", city: "Redondo Beach" }, { name: "Palisades Charter High School", city: "Los Angeles" },
    { name: "Sierra Canyon School", city: "Los Angeles" }, { name: "Harvard-Westlake School", city: "Los Angeles" },
    { name: "Bishop Montgomery High School", city: "Torrance" }, { name: "Etiwanda High School", city: "Etiwanda" },
    { name: "Chino Hills High School", city: "Chino Hills" }, { name: "Corona Centennial High School", city: "Corona" },
    { name: "Sheldon High School", city: "Sacramento" }, { name: "Modesto Christian School", city: "Modesto" },
    { name: "Berkeley High School", city: "Berkeley" }, { name: "Lincoln High School of San Diego", city: "San Diego" },
    { name: "Sacramento High School", city: "Sacramento" }, { name: "Oakland Technical High School", city: "Oakland" },
    { name: "San Leandro High School", city: "San Leandro" }, { name: "El Camino Real Charter High School", city: "Los Angeles" },
    { name: "Damien High School", city: "La Verne" }, { name: "St. John Bosco High School", city: "Bellflower" },
    { name: "Bishop O'Dowd High School", city: "Oakland" }, { name: "De La Salle High School", city: "Concord" },
  ],
  CO: [
    { name: "East High School (Denver)", city: "Denver" }, { name: "Cherry Creek High School", city: "Denver" },
    { name: "Regis Jesuit High School", city: "Aurora" }, { name: "Grandview High School", city: "Aurora" },
    { name: "Mullen High School", city: "Denver" }, { name: "Overland High School", city: "Aurora" },
    { name: "George Washington High School (Denver)", city: "Denver" }, { name: "Fairview High School", city: "Boulder" },
    { name: "Legend High School", city: "Parker" }, { name: "Eaglecrest High School", city: "Centennial" },
    { name: "Doherty High School", city: "Colorado Springs" }, { name: "Rangeview High School", city: "Aurora" },
  ],
  CT: [
    { name: "Hillhouse High School", city: "New Haven" }, { name: "Weaver High School", city: "Hartford" },
    { name: "Notre Dame High School (West Haven)", city: "West Haven" }, { name: "Xavier High School", city: "Middletown" },
    { name: "St. Joseph High School (Trumbull)", city: "Trumbull" }, { name: "Hall High School", city: "West Hartford" },
    { name: "Trinity Catholic High School", city: "Stamford" }, { name: "Hamden High School", city: "Hamden" },
    { name: "Bristol Central High School", city: "Bristol" }, { name: "Danbury High School", city: "Danbury" },
  ],
  DE: [
    { name: "Salesianum School", city: "Wilmington" }, { name: "St. Elizabeth High School", city: "Wilmington" },
    { name: "Sanford School", city: "Hockessin" }, { name: "Wilmington Friends School", city: "Wilmington" },
    { name: "Caravel Academy", city: "Bear" }, { name: "Delaware Military Academy", city: "Wilmington" },
    { name: "Sussex Central High School", city: "Georgetown" }, { name: "Dover High School", city: "Dover" },
  ],
  DC: [
    { name: "Gonzaga College High School", city: "Washington" }, { name: "St. John's College High School", city: "Washington" },
    { name: "Dunbar High School", city: "Washington" }, { name: "Wilson High School", city: "Washington" },
    { name: "Archbishop Carroll High School", city: "Washington" }, { name: "Coolidge High School", city: "Washington" },
    { name: "Ballou High School", city: "Washington" },
  ],
  FL: [
    { name: "Miami Northwestern Senior High School", city: "Miami" }, { name: "Miami Norland Senior High School", city: "Miami" },
    { name: "Miami Central Senior High School", city: "Miami" }, { name: "American Heritage School", city: "Plantation" },
    { name: "Dr. Phillips High School", city: "Orlando" }, { name: "Winter Park High School", city: "Winter Park" },
    { name: "Lake Highland Preparatory School", city: "Orlando" }, { name: "Boyd Anderson High School", city: "Fort Lauderdale" },
    { name: "Dillard High School", city: "Fort Lauderdale" }, { name: "Miami Edison Senior High School", city: "Miami" },
    { name: "Booker T. Washington High School (Miami)", city: "Miami" }, { name: "Calvary Christian Academy", city: "Fort Lauderdale" },
    { name: "University School (NSU)", city: "Fort Lauderdale" }, { name: "Palmetto Senior High School", city: "Miami" },
    { name: "Cypress Bay High School", city: "Weston" }, { name: "St. Thomas Aquinas High School", city: "Fort Lauderdale" },
    { name: "Plantation High School", city: "Plantation" }, { name: "Chaminade-Madonna College Preparatory School", city: "Hollywood" },
  ],
  GA: [
    { name: "Wheeler High School", city: "Marietta" }, { name: "Westlake High School", city: "Atlanta" },
    { name: "McEachern High School", city: "Marietta" }, { name: "Norcross High School", city: "Norcross" },
    { name: "Grayson High School", city: "Marietta" }, { name: "Berkmar High School", city: "Marietta" },
    { name: "Marietta High School", city: "Marietta" }, { name: "North Gwinnett High School", city: "Marietta" },
    { name: "Milton High School", city: "Marietta" }, { name: "Collins Hill High School", city: "Marietta" },
    { name: "Woodward Academy", city: "Atlanta" }, { name: "Westminster Schools", city: "Atlanta" },
    { name: "Pace Academy", city: "Atlanta" }, { name: "Buford High School", city: "Atlanta" },
    { name: "Colquitt County High School", city: "Marietta" },
  ],
  HI: [
    { name: "Saint Louis School", city: "Honolulu" }, { name: "Punahou School", city: "Honolulu" },
    { name: "Kamehameha Schools", city: "Honolulu" }, { name: "Iolani School", city: "Honolulu" },
    { name: "Farrington High School", city: "Honolulu" }, { name: "Kaiser High School", city: "Honolulu" },
    { name: "Mililani High School", city: "Honolulu" }, { name: "Kailua High School", city: "Kailua" },
    { name: "Roosevelt High School (Honolulu)", city: "Honolulu" },
  ],
  ID: [
    { name: "Boise High School", city: "Boise" }, { name: "Borah High School", city: "Boise" },
    { name: "Mountain View High School", city: "Boise" }, { name: "Rocky Mountain High School", city: "Boise" },
    { name: "Eagle High School", city: "Boise" }, { name: "Centennial High School (Boise)", city: "Boise" },
    { name: "Coeur d'Alene High School", city: "Coeur d'Alene" }, { name: "Timberline High School", city: "Boise" },
  ],
  IL: [
    { name: "Whitney Young High School", city: "Chicago" }, { name: "Simeon Career Academy", city: "Chicago" },
    { name: "Curie Metropolitan High School", city: "Chicago" }, { name: "Marshall Metropolitan High School", city: "Chicago" },
    { name: "Morgan Park High School", city: "Chicago" }, { name: "Young Men's Leadership Academy", city: "Chicago" },
    { name: "New Trier High School", city: "Chicago" }, { name: "Evanston Township High School", city: "Chicago" },
    { name: "Glenbard West High School", city: "Chicago" }, { name: "Waukegan High School", city: "Waukegan" },
    { name: "Proviso East High School", city: "Chicago" }, { name: "Rich East High School", city: "Chicago" },
    { name: "Bolingbrook High School", city: "Chicago" }, { name: "Peoria Manual High School", city: "Peoria" },
    { name: "St. Rita of Cascia High School", city: "Chicago" }, { name: "Fenwick High School", city: "Chicago" },
  ],
  IN: [
    { name: "Ben Davis High School", city: "Indianapolis" }, { name: "North Central High School (Indianapolis)", city: "Indianapolis" },
    { name: "Warren Central High School", city: "Indianapolis" }, { name: "Carmel High School", city: "Indianapolis" },
    { name: "Lawrence North High School", city: "Indianapolis" }, { name: "Lawrence Central High School", city: "Indianapolis" },
    { name: "Pike High School", city: "Indianapolis" }, { name: "Southport High School", city: "Indianapolis" },
    { name: "Marion High School", city: "Indianapolis" }, { name: "Fort Wayne North Side High School", city: "Fort Wayne" },
  ],
  IA: [
    { name: "Des Moines East High School", city: "Des Moines" }, { name: "Roosevelt High School (Des Moines)", city: "Des Moines" },
    { name: "Valley High School (West Des Moines)", city: "Des Moines" }, { name: "Waukee High School", city: "Des Moines" },
    { name: "Ankeny High School", city: "Des Moines" }, { name: "Dowling Catholic High School", city: "Des Moines" },
    { name: "Cedar Rapids Washington High School", city: "Cedar Rapids" }, { name: "West High School (Iowa City)", city: "Iowa City" },
  ],
  KS: [
    { name: "Wichita East High School", city: "Wichita" }, { name: "Wichita Northwest High School", city: "Wichita" },
    { name: "Blue Valley Northwest High School", city: "Overland Park" }, { name: "Olathe East High School", city: "Olathe" },
    { name: "Shawnee Mission East High School", city: "Overland Park" }, { name: "Topeka High School", city: "Topeka" },
    { name: "Bishop Miege High School", city: "Overland Park" }, { name: "Free State High School", city: "Lawrence" },
  ],
  KY: [
    { name: "Male High School", city: "Louisville" }, { name: "Trinity High School (Louisville)", city: "Louisville" },
    { name: "St. Xavier High School", city: "Louisville" }, { name: "Ballard High School", city: "Louisville" },
    { name: "Manual High School (Louisville)", city: "Louisville" }, { name: "Lexington Catholic High School", city: "Lexington" },
    { name: "Bryan Station High School", city: "Lexington" }, { name: "Christian County High School", city: "Owensboro" },
    { name: "Covington Catholic High School", city: "Covington" },
  ],
  LA: [
    { name: "Warren Easton Charter High School", city: "New Orleans" }, { name: "Edna Karr High School", city: "New Orleans" },
    { name: "St. Augustine High School", city: "New Orleans" }, { name: "John Curtis Christian School", city: "New Orleans" },
    { name: "Neville High School", city: "Monroe" }, { name: "Southern Lab High School", city: "Baton Rouge" },
    { name: "Zachary High School", city: "Baton Rouge" }, { name: "Catholic High School (Baton Rouge)", city: "Baton Rouge" },
    { name: "Archbishop Rummel High School", city: "New Orleans" }, { name: "Evangel Christian Academy", city: "Shreveport" },
  ],
  ME: [
    { name: "Deering High School", city: "Portland" }, { name: "Portland High School", city: "Portland" },
    { name: "Cheverus High School", city: "Portland" }, { name: "Bangor High School", city: "Bangor" },
    { name: "Lewiston High School", city: "Lewiston" }, { name: "South Portland High School", city: "South Portland" },
    { name: "Falmouth High School", city: "Portland" },
  ],
  MD: [
    { name: "DeMatha Catholic High School", city: "Baltimore" }, { name: "St. Frances Academy", city: "Baltimore" },
    { name: "Paul VI Catholic High School", city: "Baltimore" }, { name: "Gonzaga College High School", city: "Baltimore" },
    { name: "Dunbar High School (Baltimore)", city: "Baltimore" }, { name: "Riverdale Baptist School", city: "Silver Spring" },
    { name: "Springbrook High School", city: "Silver Spring" }, { name: "Blake High School", city: "Silver Spring" },
    { name: "Good Counsel High School", city: "Rockville" }, { name: "Whitman High School", city: "Silver Spring" },
    { name: "Wootton High School", city: "Rockville" }, { name: "Poly High School (Baltimore)", city: "Baltimore" },
    { name: "City College High School (Baltimore)", city: "Baltimore" },
  ],
  MA: [
    { name: "Boston Latin School", city: "Boston" }, { name: "English High School", city: "Boston" },
    { name: "Cathedral High School (Boston)", city: "Boston" }, { name: "Brighton High School", city: "Boston" },
    { name: "Springfield Central High School", city: "Springfield" }, { name: "Worcester South High School", city: "Worcester" },
    { name: "Cambridge Rindge and Latin School", city: "Cambridge" }, { name: "Malden Catholic High School", city: "Lynn" },
    { name: "St. John's Preparatory School", city: "Lynn" }, { name: "Catholic Memorial School", city: "Boston" },
    { name: "Newton North High School", city: "Boston" }, { name: "Brockton High School", city: "Brockton" },
  ],
  MI: [
    { name: "Cass Technical High School", city: "Detroit" }, { name: "Renaissance High School", city: "Detroit" },
    { name: "Detroit Country Day School", city: "Detroit" }, { name: "Southfield Christian School", city: "Southfield" },
    { name: "East Kentwood High School", city: "Grand Rapids" }, { name: "Ann Arbor Huron High School", city: "Ann Arbor" },
    { name: "Grand Rapids Christian High School", city: "Grand Rapids" }, { name: "Belleville High School", city: "Detroit" },
    { name: "Clarkston High School", city: "Pontiac" }, { name: "Orchard Lake St. Mary's Preparatory", city: "Pontiac" },
  ],
  MN: [
    { name: "Minneapolis North High School", city: "Minneapolis" }, { name: "Minneapolis South High School", city: "Minneapolis" },
    { name: "Hopkins High School", city: "Minneapolis" }, { name: "DeLaSalle High School", city: "Minneapolis" },
    { name: "Cretin-Derham Hall High School", city: "Saint Paul" }, { name: "Wayzata High School", city: "Minneapolis" },
    { name: "Eden Prairie High School", city: "Minneapolis" }, { name: "St. Louis Park High School", city: "Minneapolis" },
    { name: "Apple Valley High School", city: "Minneapolis" },
  ],
  MS: [
    { name: "Callaway High School", city: "Jackson" }, { name: "Murrah High School", city: "Jackson" },
    { name: "Provine High School", city: "Jackson" }, { name: "Germantown High School", city: "Jackson" },
    { name: "Oak Grove High School", city: "Hattiesburg" }, { name: "Hattiesburg High School", city: "Hattiesburg" },
    { name: "Meridian High School", city: "Meridian" }, { name: "Southaven High School", city: "Southaven" },
  ],
  MO: [
    { name: "Chaminade College Preparatory School", city: "St. Louis" }, { name: "Vashon High School", city: "St. Louis" },
    { name: "Cardinal Ritter College Preparatory High School", city: "St. Louis" }, { name: "St. Louis University High School", city: "St. Louis" },
    { name: "De Smet Jesuit High School", city: "St. Louis" }, { name: "Kickapoo High School", city: "Springfield" },
    { name: "Rockhurst High School", city: "Kansas City" }, { name: "Center High School (Kansas City)", city: "Kansas City" },
    { name: "Sumner High School", city: "St. Louis" },
  ],
  MT: [
    { name: "Billings Senior High School", city: "Billings" }, { name: "Billings West High School", city: "Billings" },
    { name: "Missoula Sentinel High School", city: "Missoula" }, { name: "Missoula Hellgate High School", city: "Missoula" },
    { name: "Great Falls High School", city: "Great Falls" }, { name: "Bozeman High School", city: "Bozeman" },
    { name: "Butte High School", city: "Butte" },
  ],
  NE: [
    { name: "Omaha Central High School", city: "Omaha" }, { name: "Omaha North High School", city: "Omaha" },
    { name: "Omaha Bryan High School", city: "Omaha" }, { name: "Lincoln High School (Nebraska)", city: "Lincoln" },
    { name: "Millard North High School", city: "Omaha" }, { name: "Creighton Preparatory School", city: "Omaha" },
    { name: "Bellevue West High School", city: "Bellevue" },
  ],
  NV: [
    { name: "Bishop Gorman High School", city: "Las Vegas" }, { name: "Findlay Prep", city: "Las Vegas" },
    { name: "Durango High School", city: "Las Vegas" }, { name: "Clark High School (Las Vegas)", city: "Las Vegas" },
    { name: "Coronado High School (Henderson)", city: "Henderson" }, { name: "Basic High School", city: "Henderson" },
    { name: "Reno High School", city: "Reno" }, { name: "Spanish Springs High School", city: "Sparks" },
  ],
  NH: [
    { name: "Manchester Central High School", city: "Manchester" }, { name: "Manchester Memorial High School", city: "Manchester" },
    { name: "Nashua High School North", city: "Nashua" }, { name: "Concord High School", city: "Concord" },
    { name: "Bishop Guertin High School", city: "Nashua" }, { name: "Pinkerton Academy", city: "Manchester" },
  ],
  NJ: [
    { name: "Roselle Catholic High School", city: "Newark" }, { name: "St. Benedict's Preparatory School", city: "Newark" },
    { name: "Camden High School", city: "Camden" }, { name: "St. Anthony High School", city: "Jersey City" },
    { name: "St. Patrick High School (Elizabeth)", city: "Elizabeth" }, { name: "Union Catholic High School", city: "Elizabeth" },
    { name: "Elizabeth High School", city: "Elizabeth" }, { name: "Newark East Side High School", city: "Newark" },
    { name: "Bergen Catholic High School", city: "Paterson" }, { name: "Don Bosco Preparatory High School", city: "Paterson" },
    { name: "Seton Hall Preparatory School", city: "Newark" }, { name: "Paterson Eastside High School", city: "Paterson" },
    { name: "Trenton Central High School", city: "Trenton" }, { name: "Hudson Catholic Regional High School", city: "Jersey City" },
  ],
  NM: [
    { name: "Albuquerque High School", city: "Albuquerque" }, { name: "Eldorado High School", city: "Albuquerque" },
    { name: "La Cueva High School", city: "Albuquerque" }, { name: "Cibola High School", city: "Albuquerque" },
    { name: "Rio Rancho High School", city: "Rio Rancho" }, { name: "Santa Fe High School", city: "Santa Fe" },
    { name: "Volcano Vista High School", city: "Albuquerque" },
  ],
  NY: [
    { name: "Long Island Lutheran", city: "New Rochelle" }, { name: "Christ the King Regional High School", city: "Queens" },
    { name: "Cardozo High School", city: "Queens" }, { name: "Boys and Girls High School", city: "Brooklyn" },
    { name: "Lincoln High School (Brooklyn)", city: "Brooklyn" }, { name: "Thomas Jefferson High School (Brooklyn)", city: "Brooklyn" },
    { name: "Rice High School", city: "New York City" }, { name: "Cardinal Hayes High School", city: "The Bronx" },
    { name: "Molloy High School", city: "Queens" }, { name: "St. Raymond High School for Boys", city: "The Bronx" },
    { name: "Xaverian High School", city: "Brooklyn" }, { name: "Bronx High School of Science", city: "The Bronx" },
    { name: "Stuyvesant High School", city: "New York City" }, { name: "Erasmus Hall High School", city: "Brooklyn" },
    { name: "Half Hollow Hills High School East", city: "New York City" }, { name: "Elmira Free Academy", city: "Utica" },
    { name: "McQuaid Jesuit High School", city: "Rochester" }, { name: "Christian Brothers Academy (Syracuse)", city: "Syracuse" },
    { name: "Niagara Falls High School", city: "Buffalo" },
  ],
  NC: [
    { name: "Word of God Christian Academy", city: "Raleigh" }, { name: "Combine Academy", city: "Charlotte" },
    { name: "Vertical Academy", city: "Charlotte" }, { name: "Christ School", city: "Asheville" },
    { name: "Providence Day School", city: "Charlotte" }, { name: "Charlotte Latin School", city: "Charlotte" },
    { name: "Independence High School", city: "Charlotte" }, { name: "Butler High School", city: "Charlotte" },
    { name: "East Mecklenburg High School", city: "Charlotte" }, { name: "Garner Magnet High School", city: "Raleigh" },
    { name: "Southeast Raleigh High School", city: "Raleigh" }, { name: "Greensboro Dudley High School", city: "Greensboro" },
    { name: "Winston-Salem Reynolds High School", city: "Winston-Salem" }, { name: "Wesleyan Christian Academy", city: "High Point" },
  ],
  ND: [
    { name: "Fargo North High School", city: "Fargo" }, { name: "Fargo South High School", city: "Fargo" },
    { name: "Bismarck High School", city: "Bismarck" }, { name: "Bismarck Century High School", city: "Bismarck" },
    { name: "Grand Forks Central High School", city: "Grand Forks" }, { name: "Minot High School", city: "Minot" },
  ],
  OH: [
    { name: "St. Vincent-St. Mary High School", city: "Akron" }, { name: "Archbishop Hoban High School", city: "Akron" },
    { name: "Cleveland Central Catholic High School", city: "Cleveland" }, { name: "Ginn Academy", city: "Cleveland" },
    { name: "Glenville High School", city: "Cleveland" }, { name: "Withrow High School", city: "Cincinnati" },
    { name: "Moeller High School", city: "Cincinnati" }, { name: "La Salle High School (Cincinnati)", city: "Cincinnati" },
    { name: "St. Edward High School", city: "Cleveland" }, { name: "Trotwood-Madison High School", city: "Dayton" },
    { name: "Findlay High School", city: "Toledo" }, { name: "Pickerington Central High School", city: "Columbus" },
    { name: "Massillon Washington High School", city: "Canton" }, { name: "Canton McKinley High School", city: "Canton" },
    { name: "Toledo Central Catholic High School", city: "Toledo" },
  ],
  OK: [
    { name: "Booker T. Washington High School (Tulsa)", city: "Tulsa" }, { name: "Douglass High School (Oklahoma City)", city: "Oklahoma City" },
    { name: "Union High School (Tulsa)", city: "Tulsa" }, { name: "Jenks High School", city: "Tulsa" },
    { name: "Edmond Memorial High School", city: "Edmond" }, { name: "Broken Arrow High School", city: "Broken Arrow" },
    { name: "Southmoore High School", city: "Moore" }, { name: "Bishop McGuinness Catholic High School", city: "Oklahoma City" },
  ],
  OR: [
    { name: "Jefferson High School (Portland)", city: "Portland" }, { name: "Grant High School (Portland)", city: "Portland" },
    { name: "Lincoln High School (Portland)", city: "Portland" }, { name: "Central Catholic High School (Portland)", city: "Portland" },
    { name: "Jesuit High School", city: "Portland" }, { name: "Sunset High School", city: "Portland" },
    { name: "West Linn High School", city: "Portland" }, { name: "South Medford High School", city: "Medford" },
  ],
  PA: [
    { name: "Roman Catholic High School", city: "Philadelphia" }, { name: "Neumann-Goretti High School", city: "Philadelphia" },
    { name: "Simon Gratz High School", city: "Philadelphia" }, { name: "West Philadelphia High School", city: "Philadelphia" },
    { name: "Imhotep Institute Charter High School", city: "Philadelphia" }, { name: "Chester High School", city: "Chester" },
    { name: "Archbishop Wood Catholic High School", city: "Philadelphia" }, { name: "La Salle College High School", city: "Philadelphia" },
    { name: "St. Joseph's Preparatory School", city: "Philadelphia" }, { name: "Reading High School", city: "Reading" },
    { name: "Erie McDowell High School", city: "Erie" }, { name: "Allderdice High School", city: "Pittsburgh" },
    { name: "Central Catholic High School (Pittsburgh)", city: "Pittsburgh" }, { name: "Aliquippa High School", city: "Pittsburgh" },
    { name: "Lincoln High School (Harrisburg)", city: "Harrisburg" },
  ],
  RI: [
    { name: "Hope High School", city: "Providence" }, { name: "Central Falls High School", city: "Providence" },
    { name: "La Salle Academy", city: "Providence" }, { name: "Mount Pleasant High School", city: "Providence" },
    { name: "Bishop Hendricken High School", city: "Warwick" }, { name: "Cranston East High School", city: "Cranston" },
  ],
  SC: [
    { name: "Wren High School", city: "Greenville" }, { name: "Dorman High School", city: "Spartanburg" },
    { name: "Byrnes High School", city: "Spartanburg" }, { name: "Hammond School", city: "Columbia" },
    { name: "Northwestern High School", city: "Rock Hill" }, { name: "Irmo High School", city: "Columbia" },
    { name: "Berkeley High School (SC)", city: "Charleston" }, { name: "Ridge View High School", city: "Columbia" },
  ],
  SD: [
    { name: "Washington High School (Sioux Falls)", city: "Sioux Falls" }, { name: "Lincoln High School (Sioux Falls)", city: "Sioux Falls" },
    { name: "Roosevelt High School (Sioux Falls)", city: "Sioux Falls" }, { name: "Rapid City Central High School", city: "Rapid City" },
    { name: "Rapid City Stevens High School", city: "Rapid City" }, { name: "Aberdeen Central High School", city: "Aberdeen" },
  ],
  TN: [
    { name: "Melrose High School", city: "Memphis" }, { name: "White Station High School", city: "Memphis" },
    { name: "East High School (Memphis)", city: "Memphis" }, { name: "Whitehaven High School", city: "Memphis" },
    { name: "Ensworth School", city: "Nashville" }, { name: "Montgomery Bell Academy", city: "Nashville" },
    { name: "Brentwood Academy", city: "Nashville" }, { name: "Oak Ridge High School", city: "Knoxville" },
    { name: "Hillsboro High School", city: "Nashville" }, { name: "Maplewood High School", city: "Nashville" },
    { name: "Father Ryan High School", city: "Nashville" },
  ],
  TX: [
    { name: "Duncanville High School", city: "Dallas" }, { name: "DeSoto High School", city: "Dallas" },
    { name: "Booker T. Washington High School for the Performing and Visual Arts", city: "Dallas" }, { name: "South Oak Cliff High School", city: "Dallas" },
    { name: "Yates High School", city: "Houston" }, { name: "Madison High School (Houston)", city: "Houston" },
    { name: "Westbury High School", city: "Houston" }, { name: "North Shore Senior High School", city: "Houston" },
    { name: "Cy-Fair High School", city: "Houston" }, { name: "Katy High School", city: "Houston" },
    { name: "Allen High School", city: "Plano" }, { name: "Prosper High School", city: "Plano" },
    { name: "Westlake High School (Austin)", city: "Austin" }, { name: "Judson High School", city: "San Antonio" },
    { name: "San Antonio Central Catholic Marianist School", city: "San Antonio" }, { name: "Lamar High School (Houston)", city: "Houston" },
    { name: "Skyline High School (Dallas)", city: "Dallas" }, { name: "Wagner High School", city: "San Antonio" },
  ],
  UT: [
    { name: "Wasatch Academy", city: "Salt Lake City" }, { name: "Bingham High School", city: "Salt Lake City" },
    { name: "Lone Peak High School", city: "Provo" }, { name: "American Fork High School", city: "Provo" },
    { name: "Timpview High School", city: "Provo" }, { name: "East High School (Salt Lake City)", city: "Salt Lake City" },
    { name: "Skyline High School (Salt Lake City)", city: "Salt Lake City" }, { name: "Corner Canyon High School", city: "Sandy" },
  ],
  VT: [
    { name: "Burlington High School", city: "Burlington" }, { name: "Rice Memorial High School", city: "South Burlington" },
    { name: "South Burlington High School", city: "South Burlington" }, { name: "Essex High School", city: "Burlington" },
    { name: "Mount Mansfield Union High School", city: "Burlington" },
  ],
  VA: [
    { name: "Oak Hill Academy", city: "Roanoke" }, { name: "Paul VI Catholic High School", city: "Alexandria" },
    { name: "Bishop O'Connell High School", city: "Alexandria" }, { name: "Woodson High School", city: "Alexandria" },
    { name: "Thomas Jefferson High School for Science and Technology", city: "Alexandria" }, { name: "Norview High School", city: "Norfolk" },
    { name: "Oscar Smith High School", city: "Chesapeake" }, { name: "Landstown High School", city: "Virginia Beach" },
    { name: "Freedom High School (South Riding)", city: "Alexandria" }, { name: "Highland Springs High School", city: "Richmond" },
    { name: "L.C. Bird High School", city: "Richmond" }, { name: "Hampton High School", city: "Hampton" },
  ],
  WA: [
    { name: "Garfield High School (Seattle)", city: "Seattle" }, { name: "Rainier Beach High School", city: "Seattle" },
    { name: "O'Dea High School", city: "Seattle" }, { name: "Franklin High School (Seattle)", city: "Seattle" },
    { name: "Bellevue High School", city: "Bellevue" }, { name: "Eastside Catholic School", city: "Bellevue" },
    { name: "Curtis High School", city: "Tacoma" }, { name: "Union High School (Camas)", city: "Vancouver" },
    { name: "Kentwood High School", city: "Federal Way" }, { name: "Federal Way High School", city: "Federal Way" },
  ],
  WV: [
    { name: "Huntington Prep", city: "Huntington" }, { name: "Huntington High School", city: "Huntington" },
    { name: "Charleston Catholic High School", city: "Charleston" }, { name: "George Washington High School (Charleston)", city: "Charleston" },
    { name: "Capital High School", city: "Charleston" }, { name: "Morgantown High School", city: "Morgantown" },
    { name: "Wheeling Central Catholic High School", city: "Wheeling" },
  ],
  WI: [
    { name: "Milwaukee Riverside University High School", city: "Milwaukee" }, { name: "Rufus King High School", city: "Milwaukee" },
    { name: "Milwaukee Vincent High School", city: "Milwaukee" }, { name: "Milwaukee King High School", city: "Milwaukee" },
    { name: "Racine St. Catherine's High School", city: "Racine" }, { name: "La Crosse Central High School", city: "Milwaukee" },
    { name: "Madison Memorial High School", city: "Madison" }, { name: "Wauwatosa East High School", city: "Milwaukee" },
    { name: "Sun Prairie High School", city: "Madison" },
  ],
  WY: [
    { name: "Cheyenne Central High School", city: "Cheyenne" }, { name: "Cheyenne East High School", city: "Cheyenne" },
    { name: "Natrona County High School", city: "Casper" }, { name: "Kelly Walsh High School", city: "Casper" },
    { name: "Laramie High School", city: "Laramie" },
  ],
};
